### ISSUE TITLE
Sentry in OCA

### ISSUE THREAD

**Issue by bealdav** [versada/odoo_sentry#5]
Hi @naglis,

Thanks for your nice sentry integration.
It was plug and play for us with your module.
Have you considered to include it in Odoo Community Association
Maybe in https://github.com/OCA/maintainer-tools 

Thanks a lot again.

**Comment by naglis** [comment]
Thanks for the feedback, @bealdav, I am really happy that you have found the module useful.

@paulius-sladkevicius, what do you think about proposing to include the module to OCA?

At the moment I see the following obstacles:

- [ ] Although we have rewritten the module from sratch, it is still a fork from [barsi/odoo_sentry](https://github.com/barsi/odoo_sentry). I guess we would need to ask the opinion/permission of the original author @barsi as well.
- [ ] Currently the module has no tests. I think we would at least need to include tests for all the helper/setup functions.
- [ ] As stated in the [known issues](https://github.com/HBEE/odoo_sentry/tree/master/odoo_sentry#known-issues) section, the module has no database separation, meaning that once installed in one DB, it would report issues for all databases. It was not a problem for us, however, I think it could be a problem for other users/environments. It might be possible to filter which DB events get emited to Sentry, but I haven't looked into it yet and can't tell if it can be done nicely.

**Comment by bealdav** [comment]
No db separation: it's documented, then all is OK. Personally, I use only 1 db on production instance. Dev or prepoduction instance are in docker.

@barsi, what do you think ?

test: Ok we could begin with few tests and community can make it grows.

**Comment by barsi** [comment]
@naglis  & @bealdav 

I'll be glad to see it been included into OCA.
you have my OK.
nice rewrite btw, I'll use your fork for my next project :+1:

**Comment by paulius-sladkevicius** [comment]
@naglis I agree too, lets include it to OCA.

**Comment by bealdav** [comment]
Nice. 

Maybe you could make a PR to https://github.com/OCA/server-tools ?

Thanks a lot

**Comment by naglis** [comment]
Ok, I'll start working on including in in OCA.

**Comment by naglis** [comment]
Made PR: OCA/server-tools#761
